// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufsrseflzasmwrvymqef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmc3JzZWZsemFzbXdydnltcWVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODAyNTcsImV4cCI6MjA1OTI1NjI1N30.jps2Eim-sGgyRGz-WmNL7L6AjJt5Q28i6iUkR4u1C4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);